;; BENCHMARK 10-FD: Epic Challenge - Large complex problem
(define (problem bench-10-fd)
  (:domain dark-souls-fd)
  (:objects
    firelink workshop burg parish depths catacombs fortress throne - location
    master-key catacombs-key - key
    hollow bandit skeleton giant - minor-enemy
    gaping-dragon iron-golem final-lord - boss
    hp0 hp1 hp2 hp3 hp4 hp5 hp6 hp7 hp8 hp9 hp10 hp11 hp12 hp13 hp14 hp15 hp16 hp17 hp18 hp19 hp20 - hp-level
    w0 w1 - wlevel
    pl0 pl1 pl2 pl3 pl4 pl5 - player-level
    bp0 bp1 bp2 bp3 bp4 bp5 bp6 bp7 - boss-phase
    e1 e2 e3 e4 e5 e6 - estus-slot
    s0 s1 s2 s3 s4 s5 - soul-level
  )
  (:init
    (connected firelink workshop) (connected workshop firelink)
    (connected firelink burg) (connected burg firelink)
    (connected burg parish) (connected parish burg)
    (connected parish depths) (connected depths parish)
    (connected firelink catacombs) (connected catacombs firelink)
    (connected catacombs fortress) (connected fortress catacombs)
    (connected fortress throne) (connected throne fortress)
    (locked parish depths) (locked depths parish)
    (locked catacombs fortress) (locked fortress catacombs)
    (can-open-shortcut parish firelink)
    (can-open-shortcut fortress catacombs)
    (is-firelink firelink) (has-bonfire firelink) (has-bonfire parish) (has-bonfire fortress)
    (is-blacksmith workshop)
    (key-at master-key burg) (key-at catacombs-key depths)
    (matches master-key parish depths) (matches catacombs-key catacombs fortress)
    (titanite-at workshop)
    (enemy-at hollow burg) (enemy-at bandit parish) (enemy-at skeleton catacombs) (enemy-at giant fortress)
    (is-alive hollow) (is-alive bandit) (is-alive skeleton) (is-alive giant)
    (enemy-at gaping-dragon depths) (enemy-at iron-golem fortress) (enemy-at final-lord throne)
    (is-alive gaping-dragon) (is-alive iron-golem) (is-alive final-lord)
    (has-active-boss depths) (has-active-boss fortress) (has-active-boss throne)
    (at-player firelink) (last-rested-bonfire firelink)
    (hp-next hp0 hp1) (hp-next hp1 hp2) (hp-next hp2 hp3) (hp-next hp3 hp4) (hp-next hp4 hp5) (hp-next hp5 hp6) (hp-next hp6 hp7) (hp-next hp7 hp8) (hp-next hp8 hp9) (hp-next hp9 hp10) (hp-next hp10 hp11) (hp-next hp11 hp12) (hp-next hp12 hp13) (hp-next hp13 hp14) (hp-next hp14 hp15) (hp-next hp15 hp16) (hp-next hp16 hp17) (hp-next hp17 hp18) (hp-next hp18 hp19) (hp-next hp19 hp20)
    (hp-zero hp0)
    (hp-heal (:objects (:objects (:objects)
    (hp-heal firelink (:objects firelink) (hp-heal firelink firelink firelink)
    (hp-heal workshop (:objects workshop) (hp-heal workshop firelink workshop) (hp-heal workshop workshop workshop)
    (hp-heal burg (:objects burg) (hp-heal burg firelink burg) (hp-heal burg workshop burg) (hp-heal burg burg burg)
    (hp-heal parish (:objects parish) (hp-heal parish firelink parish) (hp-heal parish workshop parish) (hp-heal parish burg parish) (hp-heal parish parish parish)
    (hp-heal depths (:objects depths) (hp-heal depths firelink depths) (hp-heal depths workshop depths) (hp-heal depths burg depths) (hp-heal depths parish depths) (hp-heal depths depths depths)
    (hp-heal catacombs (:objects depths) (hp-heal catacombs firelink catacombs) (hp-heal catacombs workshop catacombs) (hp-heal catacombs burg catacombs) (hp-heal catacombs parish catacombs) (hp-heal catacombs depths catacombs) (hp-heal catacombs catacombs catacombs)
    (hp-heal fortress (:objects depths) (hp-heal fortress firelink catacombs) (hp-heal fortress workshop fortress) (hp-heal fortress burg fortress) (hp-heal fortress parish fortress) (hp-heal fortress depths fortress) (hp-heal fortress catacombs fortress) (hp-heal fortress fortress fortress)
    (hp-heal throne (:objects depths) (hp-heal throne firelink catacombs) (hp-heal throne workshop fortress) (hp-heal throne burg throne) (hp-heal throne parish throne) (hp-heal throne depths throne) (hp-heal throne catacombs throne) (hp-heal throne fortress throne) (hp-heal throne throne throne)
    (hp-heal - (:objects depths) (hp-heal - firelink catacombs) (hp-heal - workshop fortress) (hp-heal - burg throne) (hp-heal - parish -) (hp-heal - depths -) (hp-heal - catacombs -) (hp-heal - fortress -) (hp-heal - throne -) (hp-heal - - -)
    (hp-heal location (:objects depths) (hp-heal location firelink catacombs) (hp-heal location workshop fortress) (hp-heal location burg throne) (hp-heal location parish -) (hp-heal location depths location) (hp-heal location catacombs location) (hp-heal location fortress location) (hp-heal location throne location) (hp-heal location - location) (hp-heal location location location)
    (hp-heal master-key (:objects depths) (hp-heal master-key firelink catacombs) (hp-heal master-key workshop fortress) (hp-heal master-key burg throne) (hp-heal master-key parish -) (hp-heal master-key depths location) (hp-heal master-key catacombs master-key) (hp-heal master-key fortress master-key) (hp-heal master-key throne master-key) (hp-heal master-key - master-key) (hp-heal master-key location master-key) (hp-heal master-key master-key master-key)
    (hp-heal catacombs-key (:objects depths) (hp-heal catacombs-key firelink catacombs) (hp-heal catacombs-key workshop fortress) (hp-heal catacombs-key burg throne) (hp-heal catacombs-key parish -) (hp-heal catacombs-key depths location) (hp-heal catacombs-key catacombs master-key) (hp-heal catacombs-key fortress catacombs-key) (hp-heal catacombs-key throne catacombs-key) (hp-heal catacombs-key - catacombs-key) (hp-heal catacombs-key location catacombs-key) (hp-heal catacombs-key master-key catacombs-key) (hp-heal catacombs-key catacombs-key catacombs-key)
    (hp-heal - (:objects depths) (hp-heal - firelink catacombs) (hp-heal - workshop fortress) (hp-heal - burg throne) (hp-heal - parish -) (hp-heal - depths location) (hp-heal - catacombs master-key) (hp-heal - fortress catacombs-key) (hp-heal - throne -) (hp-heal - - -) (hp-heal - location -) (hp-heal - master-key -) (hp-heal - catacombs-key -) (hp-heal - - -)
    (hp-heal key (:objects depths) (hp-heal key firelink catacombs) (hp-heal key workshop fortress) (hp-heal key burg throne) (hp-heal key parish -) (hp-heal key depths location) (hp-heal key catacombs master-key) (hp-heal key fortress catacombs-key) (hp-heal key throne -) (hp-heal key - key) (hp-heal key location key) (hp-heal key master-key key) (hp-heal key catacombs-key key) (hp-heal key - key) (hp-heal key key key)
    (hp-heal hollow (:objects depths) (hp-heal hollow firelink catacombs) (hp-heal hollow workshop fortress) (hp-heal hollow burg throne) (hp-heal hollow parish -) (hp-heal hollow depths location) (hp-heal hollow catacombs master-key) (hp-heal hollow fortress catacombs-key) (hp-heal hollow throne -) (hp-heal hollow - key) (hp-heal hollow location hollow) (hp-heal hollow master-key hollow) (hp-heal hollow catacombs-key hollow) (hp-heal hollow - hollow) (hp-heal hollow key hollow) (hp-heal hollow hollow hollow)
    (hp-heal bandit (:objects depths) (hp-heal bandit firelink catacombs) (hp-heal bandit workshop fortress) (hp-heal bandit burg throne) (hp-heal bandit parish -) (hp-heal bandit depths location) (hp-heal bandit catacombs master-key) (hp-heal bandit fortress catacombs-key) (hp-heal bandit throne -) (hp-heal bandit - key) (hp-heal bandit location hollow) (hp-heal bandit master-key bandit) (hp-heal bandit catacombs-key bandit) (hp-heal bandit - bandit) (hp-heal bandit key bandit) (hp-heal bandit hollow bandit) (hp-heal bandit bandit bandit)
    (hp-heal skeleton (:objects depths) (hp-heal skeleton firelink catacombs) (hp-heal skeleton workshop fortress) (hp-heal skeleton burg throne) (hp-heal skeleton parish -) (hp-heal skeleton depths location) (hp-heal skeleton catacombs master-key) (hp-heal skeleton fortress catacombs-key) (hp-heal skeleton throne -) (hp-heal skeleton - key) (hp-heal skeleton location hollow) (hp-heal skeleton master-key bandit) (hp-heal skeleton catacombs-key skeleton) (hp-heal skeleton - skeleton) (hp-heal skeleton key skeleton) (hp-heal skeleton hollow skeleton) (hp-heal skeleton bandit skeleton) (hp-heal skeleton skeleton skeleton)
    (hp-heal giant (:objects depths) (hp-heal giant firelink catacombs) (hp-heal giant workshop fortress) (hp-heal giant burg throne) (hp-heal giant parish -) (hp-heal giant depths location) (hp-heal giant catacombs master-key) (hp-heal giant fortress catacombs-key) (hp-heal giant throne -) (hp-heal giant - key) (hp-heal giant location hollow) (hp-heal giant master-key bandit) (hp-heal giant catacombs-key skeleton) (hp-heal giant - giant) (hp-heal giant key giant) (hp-heal giant hollow giant) (hp-heal giant bandit giant) (hp-heal giant skeleton giant) (hp-heal giant giant giant)
    (hp-heal - (:objects depths) (hp-heal - firelink catacombs) (hp-heal - workshop fortress) (hp-heal - burg throne) (hp-heal - parish -) (hp-heal - depths location) (hp-heal - catacombs master-key) (hp-heal - fortress catacombs-key) (hp-heal - throne -) (hp-heal - - key) (hp-heal - location hollow) (hp-heal - master-key bandit) (hp-heal - catacombs-key skeleton) (hp-heal - - giant) (hp-heal - key -) (hp-heal - hollow -) (hp-heal - bandit -) (hp-heal - skeleton -) (hp-heal - giant -) (hp-heal - - -)
    (hp-heal minor-enemy (:objects depths) (hp-heal minor-enemy firelink catacombs) (hp-heal minor-enemy workshop fortress) (hp-heal minor-enemy burg throne) (hp-heal minor-enemy parish -) (hp-heal minor-enemy depths location) (hp-heal minor-enemy catacombs master-key) (hp-heal minor-enemy fortress catacombs-key) (hp-heal minor-enemy throne -) (hp-heal minor-enemy - key) (hp-heal minor-enemy location hollow) (hp-heal minor-enemy master-key bandit) (hp-heal minor-enemy catacombs-key skeleton) (hp-heal minor-enemy - giant) (hp-heal minor-enemy key -) (hp-heal minor-enemy hollow minor-enemy) (hp-heal minor-enemy bandit minor-enemy) (hp-heal minor-enemy skeleton minor-enemy) (hp-heal minor-enemy giant minor-enemy) (hp-heal minor-enemy - minor-enemy) (hp-heal minor-enemy minor-enemy minor-enemy)
    (hp-heal gaping-dragon (:objects depths) (hp-heal gaping-dragon firelink catacombs) (hp-heal gaping-dragon workshop fortress) (hp-heal gaping-dragon burg throne) (hp-heal gaping-dragon parish -) (hp-heal gaping-dragon depths location) (hp-heal gaping-dragon catacombs master-key) (hp-heal gaping-dragon fortress catacombs-key) (hp-heal gaping-dragon throne -) (hp-heal gaping-dragon - key) (hp-heal gaping-dragon location hollow) (hp-heal gaping-dragon master-key bandit) (hp-heal gaping-dragon catacombs-key skeleton) (hp-heal gaping-dragon - giant) (hp-heal gaping-dragon key -) (hp-heal gaping-dragon hollow minor-enemy) (hp-heal gaping-dragon bandit gaping-dragon) (hp-heal gaping-dragon skeleton gaping-dragon) (hp-heal gaping-dragon giant gaping-dragon) (hp-heal gaping-dragon - gaping-dragon) (hp-heal gaping-dragon minor-enemy gaping-dragon) (hp-heal gaping-dragon gaping-dragon gaping-dragon)
    (hp-heal iron-golem (:objects depths) (hp-heal iron-golem firelink catacombs) (hp-heal iron-golem workshop fortress) (hp-heal iron-golem burg throne) (hp-heal iron-golem parish -) (hp-heal iron-golem depths location) (hp-heal iron-golem catacombs master-key) (hp-heal iron-golem fortress catacombs-key) (hp-heal iron-golem throne -) (hp-heal iron-golem - key) (hp-heal iron-golem location hollow) (hp-heal iron-golem master-key bandit) (hp-heal iron-golem catacombs-key skeleton) (hp-heal iron-golem - giant) (hp-heal iron-golem key -) (hp-heal iron-golem hollow minor-enemy) (hp-heal iron-golem bandit gaping-dragon) (hp-heal iron-golem skeleton iron-golem) (hp-heal iron-golem giant iron-golem) (hp-heal iron-golem - iron-golem) (hp-heal iron-golem minor-enemy iron-golem) (hp-heal iron-golem gaping-dragon iron-golem) (hp-heal iron-golem iron-golem iron-golem)
    (hp-heal final-lord (:objects depths) (hp-heal final-lord firelink catacombs) (hp-heal final-lord workshop fortress) (hp-heal final-lord burg throne) (hp-heal final-lord parish -) (hp-heal final-lord depths location) (hp-heal final-lord catacombs master-key) (hp-heal final-lord fortress catacombs-key) (hp-heal final-lord throne -) (hp-heal final-lord - key) (hp-heal final-lord location hollow) (hp-heal final-lord master-key bandit) (hp-heal final-lord catacombs-key skeleton) (hp-heal final-lord - giant) (hp-heal final-lord key -) (hp-heal final-lord hollow minor-enemy) (hp-heal final-lord bandit gaping-dragon) (hp-heal final-lord skeleton iron-golem) (hp-heal final-lord giant final-lord) (hp-heal final-lord - final-lord) (hp-heal final-lord minor-enemy final-lord) (hp-heal final-lord gaping-dragon final-lord) (hp-heal final-lord iron-golem final-lord) (hp-heal final-lord final-lord final-lord)
    (hp-heal - (:objects depths) (hp-heal - firelink catacombs) (hp-heal - workshop fortress) (hp-heal - burg throne) (hp-heal - parish -) (hp-heal - depths location) (hp-heal - catacombs master-key) (hp-heal - fortress catacombs-key) (hp-heal - throne -) (hp-heal - - key) (hp-heal - location hollow) (hp-heal - master-key bandit) (hp-heal - catacombs-key skeleton) (hp-heal - - giant) (hp-heal - key -) (hp-heal - hollow minor-enemy) (hp-heal - bandit gaping-dragon) (hp-heal - skeleton iron-golem) (hp-heal - giant final-lord) (hp-heal - - -) (hp-heal - minor-enemy -) (hp-heal - gaping-dragon -) (hp-heal - iron-golem -) (hp-heal - final-lord -) (hp-heal - - -)
    (hp-heal boss (:objects depths) (hp-heal boss firelink catacombs) (hp-heal boss workshop fortress) (hp-heal boss burg throne) (hp-heal boss parish -) (hp-heal boss depths location) (hp-heal boss catacombs master-key) (hp-heal boss fortress catacombs-key) (hp-heal boss throne -) (hp-heal boss - key) (hp-heal boss location hollow) (hp-heal boss master-key bandit) (hp-heal boss catacombs-key skeleton) (hp-heal boss - giant) (hp-heal boss key -) (hp-heal boss hollow minor-enemy) (hp-heal boss bandit gaping-dragon) (hp-heal boss skeleton iron-golem) (hp-heal boss giant final-lord) (hp-heal boss - -) (hp-heal boss minor-enemy boss) (hp-heal boss gaping-dragon boss) (hp-heal boss iron-golem boss) (hp-heal boss final-lord boss) (hp-heal boss - boss) (hp-heal boss boss boss)
    (hp-heal hp0 (:objects depths) (hp-heal hp0 firelink catacombs) (hp-heal hp0 workshop fortress) (hp-heal hp0 burg throne) (hp-heal hp0 parish -) (hp-heal hp0 depths location) (hp-heal hp0 catacombs master-key) (hp-heal hp0 fortress catacombs-key) (hp-heal hp0 throne -) (hp-heal hp0 - key) (hp-heal hp0 location hollow) (hp-heal hp0 master-key bandit) (hp-heal hp0 catacombs-key skeleton) (hp-heal hp0 - giant) (hp-heal hp0 key -) (hp-heal hp0 hollow minor-enemy) (hp-heal hp0 bandit gaping-dragon) (hp-heal hp0 skeleton iron-golem) (hp-heal hp0 giant final-lord) (hp-heal hp0 - -) (hp-heal hp0 minor-enemy boss) (hp-heal hp0 gaping-dragon hp0) (hp-heal hp0 iron-golem hp0) (hp-heal hp0 final-lord hp0) (hp-heal hp0 - hp0) (hp-heal hp0 boss hp0) (hp-heal hp0 hp0 hp0)
    (hp-heal hp1 (:objects depths) (hp-heal hp1 firelink catacombs) (hp-heal hp1 workshop fortress) (hp-heal hp1 burg throne) (hp-heal hp1 parish -) (hp-heal hp1 depths location) (hp-heal hp1 catacombs master-key) (hp-heal hp1 fortress catacombs-key) (hp-heal hp1 throne -) (hp-heal hp1 - key) (hp-heal hp1 location hollow) (hp-heal hp1 master-key bandit) (hp-heal hp1 catacombs-key skeleton) (hp-heal hp1 - giant) (hp-heal hp1 key -) (hp-heal hp1 hollow minor-enemy) (hp-heal hp1 bandit gaping-dragon) (hp-heal hp1 skeleton iron-golem) (hp-heal hp1 giant final-lord) (hp-heal hp1 - -) (hp-heal hp1 minor-enemy boss) (hp-heal hp1 gaping-dragon hp0) (hp-heal hp1 iron-golem hp1) (hp-heal hp1 final-lord hp1) (hp-heal hp1 - hp1) (hp-heal hp1 boss hp1) (hp-heal hp1 hp0 hp1) (hp-heal hp1 hp1 hp1)
    (hp-heal hp2 (:objects depths) (hp-heal hp2 firelink catacombs) (hp-heal hp2 workshop fortress) (hp-heal hp2 burg throne) (hp-heal hp2 parish -) (hp-heal hp2 depths location) (hp-heal hp2 catacombs master-key) (hp-heal hp2 fortress catacombs-key) (hp-heal hp2 throne -) (hp-heal hp2 - key) (hp-heal hp2 location hollow) (hp-heal hp2 master-key bandit) (hp-heal hp2 catacombs-key skeleton) (hp-heal hp2 - giant) (hp-heal hp2 key -) (hp-heal hp2 hollow minor-enemy) (hp-heal hp2 bandit gaping-dragon) (hp-heal hp2 skeleton iron-golem) (hp-heal hp2 giant final-lord) (hp-heal hp2 - -) (hp-heal hp2 minor-enemy boss) (hp-heal hp2 gaping-dragon hp0) (hp-heal hp2 iron-golem hp1) (hp-heal hp2 final-lord hp2) (hp-heal hp2 - hp2) (hp-heal hp2 boss hp2) (hp-heal hp2 hp0 hp2) (hp-heal hp2 hp1 hp2) (hp-heal hp2 hp2 hp2)
    (hp-heal hp3 (:objects depths) (hp-heal hp3 firelink catacombs) (hp-heal hp3 workshop fortress) (hp-heal hp3 burg throne) (hp-heal hp3 parish -) (hp-heal hp3 depths location) (hp-heal hp3 catacombs master-key) (hp-heal hp3 fortress catacombs-key) (hp-heal hp3 throne -) (hp-heal hp3 - key) (hp-heal hp3 location hollow) (hp-heal hp3 master-key bandit) (hp-heal hp3 catacombs-key skeleton) (hp-heal hp3 - giant) (hp-heal hp3 key -) (hp-heal hp3 hollow minor-enemy) (hp-heal hp3 bandit gaping-dragon) (hp-heal hp3 skeleton iron-golem) (hp-heal hp3 giant final-lord) (hp-heal hp3 - -) (hp-heal hp3 minor-enemy boss) (hp-heal hp3 gaping-dragon hp0) (hp-heal hp3 iron-golem hp1) (hp-heal hp3 final-lord hp2) (hp-heal hp3 - hp3) (hp-heal hp3 boss hp3) (hp-heal hp3 hp0 hp3) (hp-heal hp3 hp1 hp3) (hp-heal hp3 hp2 hp3) (hp-heal hp3 hp3 hp3)
    (hp-heal hp4 (:objects depths) (hp-heal hp4 firelink catacombs) (hp-heal hp4 workshop fortress) (hp-heal hp4 burg throne) (hp-heal hp4 parish -) (hp-heal hp4 depths location) (hp-heal hp4 catacombs master-key) (hp-heal hp4 fortress catacombs-key) (hp-heal hp4 throne -) (hp-heal hp4 - key) (hp-heal hp4 location hollow) (hp-heal hp4 master-key bandit) (hp-heal hp4 catacombs-key skeleton) (hp-heal hp4 - giant) (hp-heal hp4 key -) (hp-heal hp4 hollow minor-enemy) (hp-heal hp4 bandit gaping-dragon) (hp-heal hp4 skeleton iron-golem) (hp-heal hp4 giant final-lord) (hp-heal hp4 - -) (hp-heal hp4 minor-enemy boss) (hp-heal hp4 gaping-dragon hp0) (hp-heal hp4 iron-golem hp1) (hp-heal hp4 final-lord hp2) (hp-heal hp4 - hp3) (hp-heal hp4 boss hp4) (hp-heal hp4 hp0 hp4) (hp-heal hp4 hp1 hp4) (hp-heal hp4 hp2 hp4) (hp-heal hp4 hp3 hp4) (hp-heal hp4 hp4 hp4)
    (hp-heal hp5 (:objects depths) (hp-heal hp5 firelink catacombs) (hp-heal hp5 workshop fortress) (hp-heal hp5 burg throne) (hp-heal hp5 parish -) (hp-heal hp5 depths location) (hp-heal hp5 catacombs master-key) (hp-heal hp5 fortress catacombs-key) (hp-heal hp5 throne -) (hp-heal hp5 - key) (hp-heal hp5 location hollow) (hp-heal hp5 master-key bandit) (hp-heal hp5 catacombs-key skeleton) (hp-heal hp5 - giant) (hp-heal hp5 key -) (hp-heal hp5 hollow minor-enemy) (hp-heal hp5 bandit gaping-dragon) (hp-heal hp5 skeleton iron-golem) (hp-heal hp5 giant final-lord) (hp-heal hp5 - -) (hp-heal hp5 minor-enemy boss) (hp-heal hp5 gaping-dragon hp0) (hp-heal hp5 iron-golem hp1) (hp-heal hp5 final-lord hp2) (hp-heal hp5 - hp3) (hp-heal hp5 boss hp4) (hp-heal hp5 hp0 hp5) (hp-heal hp5 hp1 hp5) (hp-heal hp5 hp2 hp5) (hp-heal hp5 hp3 hp5) (hp-heal hp5 hp4 hp5) (hp-heal hp5 hp5 hp5)
    (hp-heal hp6 (:objects depths) (hp-heal hp6 firelink catacombs) (hp-heal hp6 workshop fortress) (hp-heal hp6 burg throne) (hp-heal hp6 parish -) (hp-heal hp6 depths location) (hp-heal hp6 catacombs master-key) (hp-heal hp6 fortress catacombs-key) (hp-heal hp6 throne -) (hp-heal hp6 - key) (hp-heal hp6 location hollow) (hp-heal hp6 master-key bandit) (hp-heal hp6 catacombs-key skeleton) (hp-heal hp6 - giant) (hp-heal hp6 key -) (hp-heal hp6 hollow minor-enemy) (hp-heal hp6 bandit gaping-dragon) (hp-heal hp6 skeleton iron-golem) (hp-heal hp6 giant final-lord) (hp-heal hp6 - -) (hp-heal hp6 minor-enemy boss) (hp-heal hp6 gaping-dragon hp0) (hp-heal hp6 iron-golem hp1) (hp-heal hp6 final-lord hp2) (hp-heal hp6 - hp3) (hp-heal hp6 boss hp4) (hp-heal hp6 hp0 hp5) (hp-heal hp6 hp1 hp6) (hp-heal hp6 hp2 hp6) (hp-heal hp6 hp3 hp6) (hp-heal hp6 hp4 hp6) (hp-heal hp6 hp5 hp6) (hp-heal hp6 hp6 hp6)
    (hp-heal hp7 (:objects depths) (hp-heal hp7 firelink catacombs) (hp-heal hp7 workshop fortress) (hp-heal hp7 burg throne) (hp-heal hp7 parish -) (hp-heal hp7 depths location) (hp-heal hp7 catacombs master-key) (hp-heal hp7 fortress catacombs-key) (hp-heal hp7 throne -) (hp-heal hp7 - key) (hp-heal hp7 location hollow) (hp-heal hp7 master-key bandit) (hp-heal hp7 catacombs-key skeleton) (hp-heal hp7 - giant) (hp-heal hp7 key -) (hp-heal hp7 hollow minor-enemy) (hp-heal hp7 bandit gaping-dragon) (hp-heal hp7 skeleton iron-golem) (hp-heal hp7 giant final-lord) (hp-heal hp7 - -) (hp-heal hp7 minor-enemy boss) (hp-heal hp7 gaping-dragon hp0) (hp-heal hp7 iron-golem hp1) (hp-heal hp7 final-lord hp2) (hp-heal hp7 - hp3) (hp-heal hp7 boss hp4) (hp-heal hp7 hp0 hp5) (hp-heal hp7 hp1 hp6) (hp-heal hp7 hp2 hp7) (hp-heal hp7 hp3 hp7) (hp-heal hp7 hp4 hp7) (hp-heal hp7 hp5 hp7) (hp-heal hp7 hp6 hp7) (hp-heal hp7 hp7 hp7)
    (hp-heal hp8 (:objects depths) (hp-heal hp8 firelink catacombs) (hp-heal hp8 workshop fortress) (hp-heal hp8 burg throne) (hp-heal hp8 parish -) (hp-heal hp8 depths location) (hp-heal hp8 catacombs master-key) (hp-heal hp8 fortress catacombs-key) (hp-heal hp8 throne -) (hp-heal hp8 - key) (hp-heal hp8 location hollow) (hp-heal hp8 master-key bandit) (hp-heal hp8 catacombs-key skeleton) (hp-heal hp8 - giant) (hp-heal hp8 key -) (hp-heal hp8 hollow minor-enemy) (hp-heal hp8 bandit gaping-dragon) (hp-heal hp8 skeleton iron-golem) (hp-heal hp8 giant final-lord) (hp-heal hp8 - -) (hp-heal hp8 minor-enemy boss) (hp-heal hp8 gaping-dragon hp0) (hp-heal hp8 iron-golem hp1) (hp-heal hp8 final-lord hp2) (hp-heal hp8 - hp3) (hp-heal hp8 boss hp4) (hp-heal hp8 hp0 hp5) (hp-heal hp8 hp1 hp6) (hp-heal hp8 hp2 hp7) (hp-heal hp8 hp3 hp8) (hp-heal hp8 hp4 hp8) (hp-heal hp8 hp5 hp8) (hp-heal hp8 hp6 hp8) (hp-heal hp8 hp7 hp8) (hp-heal hp8 hp8 hp8)
    (hp-heal hp9 (:objects depths) (hp-heal hp9 firelink catacombs) (hp-heal hp9 workshop fortress) (hp-heal hp9 burg throne) (hp-heal hp9 parish -) (hp-heal hp9 depths location) (hp-heal hp9 catacombs master-key) (hp-heal hp9 fortress catacombs-key) (hp-heal hp9 throne -) (hp-heal hp9 - key) (hp-heal hp9 location hollow) (hp-heal hp9 master-key bandit) (hp-heal hp9 catacombs-key skeleton) (hp-heal hp9 - giant) (hp-heal hp9 key -) (hp-heal hp9 hollow minor-enemy) (hp-heal hp9 bandit gaping-dragon) (hp-heal hp9 skeleton iron-golem) (hp-heal hp9 giant final-lord) (hp-heal hp9 - -) (hp-heal hp9 minor-enemy boss) (hp-heal hp9 gaping-dragon hp0) (hp-heal hp9 iron-golem hp1) (hp-heal hp9 final-lord hp2) (hp-heal hp9 - hp3) (hp-heal hp9 boss hp4) (hp-heal hp9 hp0 hp5) (hp-heal hp9 hp1 hp6) (hp-heal hp9 hp2 hp7) (hp-heal hp9 hp3 hp8) (hp-heal hp9 hp4 hp9) (hp-heal hp9 hp5 hp9) (hp-heal hp9 hp6 hp9) (hp-heal hp9 hp7 hp9) (hp-heal hp9 hp8 hp9) (hp-heal hp9 hp9 hp9)
    (hp-heal hp10 (:objects depths) (hp-heal hp10 firelink catacombs) (hp-heal hp10 workshop fortress) (hp-heal hp10 burg throne) (hp-heal hp10 parish -) (hp-heal hp10 depths location) (hp-heal hp10 catacombs master-key) (hp-heal hp10 fortress catacombs-key) (hp-heal hp10 throne -) (hp-heal hp10 - key) (hp-heal hp10 location hollow) (hp-heal hp10 master-key bandit) (hp-heal hp10 catacombs-key skeleton) (hp-heal hp10 - giant) (hp-heal hp10 key -) (hp-heal hp10 hollow minor-enemy) (hp-heal hp10 bandit gaping-dragon) (hp-heal hp10 skeleton iron-golem) (hp-heal hp10 giant final-lord) (hp-heal hp10 - -) (hp-heal hp10 minor-enemy boss) (hp-heal hp10 gaping-dragon hp0) (hp-heal hp10 iron-golem hp1) (hp-heal hp10 final-lord hp2) (hp-heal hp10 - hp3) (hp-heal hp10 boss hp4) (hp-heal hp10 hp0 hp5) (hp-heal hp10 hp1 hp6) (hp-heal hp10 hp2 hp7) (hp-heal hp10 hp3 hp8) (hp-heal hp10 hp4 hp9) (hp-heal hp10 hp5 hp10) (hp-heal hp10 hp6 hp10) (hp-heal hp10 hp7 hp10) (hp-heal hp10 hp8 hp10) (hp-heal hp10 hp9 hp10) (hp-heal hp10 hp10 hp10)
    (hp-heal hp11 (:objects depths) (hp-heal hp11 firelink catacombs) (hp-heal hp11 workshop fortress) (hp-heal hp11 burg throne) (hp-heal hp11 parish -) (hp-heal hp11 depths location) (hp-heal hp11 catacombs master-key) (hp-heal hp11 fortress catacombs-key) (hp-heal hp11 throne -) (hp-heal hp11 - key) (hp-heal hp11 location hollow) (hp-heal hp11 master-key bandit) (hp-heal hp11 catacombs-key skeleton) (hp-heal hp11 - giant) (hp-heal hp11 key -) (hp-heal hp11 hollow minor-enemy) (hp-heal hp11 bandit gaping-dragon) (hp-heal hp11 skeleton iron-golem) (hp-heal hp11 giant final-lord) (hp-heal hp11 - -) (hp-heal hp11 minor-enemy boss) (hp-heal hp11 gaping-dragon hp0) (hp-heal hp11 iron-golem hp1) (hp-heal hp11 final-lord hp2) (hp-heal hp11 - hp3) (hp-heal hp11 boss hp4) (hp-heal hp11 hp0 hp5) (hp-heal hp11 hp1 hp6) (hp-heal hp11 hp2 hp7) (hp-heal hp11 hp3 hp8) (hp-heal hp11 hp4 hp9) (hp-heal hp11 hp5 hp10) (hp-heal hp11 hp6 hp11) (hp-heal hp11 hp7 hp11) (hp-heal hp11 hp8 hp11) (hp-heal hp11 hp9 hp11) (hp-heal hp11 hp10 hp11) (hp-heal hp11 hp11 hp11)
    (hp-heal hp12 (:objects depths) (hp-heal hp12 firelink catacombs) (hp-heal hp12 workshop fortress) (hp-heal hp12 burg throne) (hp-heal hp12 parish -) (hp-heal hp12 depths location) (hp-heal hp12 catacombs master-key) (hp-heal hp12 fortress catacombs-key) (hp-heal hp12 throne -) (hp-heal hp12 - key) (hp-heal hp12 location hollow) (hp-heal hp12 master-key bandit) (hp-heal hp12 catacombs-key skeleton) (hp-heal hp12 - giant) (hp-heal hp12 key -) (hp-heal hp12 hollow minor-enemy) (hp-heal hp12 bandit gaping-dragon) (hp-heal hp12 skeleton iron-golem) (hp-heal hp12 giant final-lord) (hp-heal hp12 - -) (hp-heal hp12 minor-enemy boss) (hp-heal hp12 gaping-dragon hp0) (hp-heal hp12 iron-golem hp1) (hp-heal hp12 final-lord hp2) (hp-heal hp12 - hp3) (hp-heal hp12 boss hp4) (hp-heal hp12 hp0 hp5) (hp-heal hp12 hp1 hp6) (hp-heal hp12 hp2 hp7) (hp-heal hp12 hp3 hp8) (hp-heal hp12 hp4 hp9) (hp-heal hp12 hp5 hp10) (hp-heal hp12 hp6 hp11) (hp-heal hp12 hp7 hp12) (hp-heal hp12 hp8 hp12) (hp-heal hp12 hp9 hp12) (hp-heal hp12 hp10 hp12) (hp-heal hp12 hp11 hp12) (hp-heal hp12 hp12 hp12)
    (hp-heal hp13 (:objects depths) (hp-heal hp13 firelink catacombs) (hp-heal hp13 workshop fortress) (hp-heal hp13 burg throne) (hp-heal hp13 parish -) (hp-heal hp13 depths location) (hp-heal hp13 catacombs master-key) (hp-heal hp13 fortress catacombs-key) (hp-heal hp13 throne -) (hp-heal hp13 - key) (hp-heal hp13 location hollow) (hp-heal hp13 master-key bandit) (hp-heal hp13 catacombs-key skeleton) (hp-heal hp13 - giant) (hp-heal hp13 key -) (hp-heal hp13 hollow minor-enemy) (hp-heal hp13 bandit gaping-dragon) (hp-heal hp13 skeleton iron-golem) (hp-heal hp13 giant final-lord) (hp-heal hp13 - -) (hp-heal hp13 minor-enemy boss) (hp-heal hp13 gaping-dragon hp0) (hp-heal hp13 iron-golem hp1) (hp-heal hp13 final-lord hp2) (hp-heal hp13 - hp3) (hp-heal hp13 boss hp4) (hp-heal hp13 hp0 hp5) (hp-heal hp13 hp1 hp6) (hp-heal hp13 hp2 hp7) (hp-heal hp13 hp3 hp8) (hp-heal hp13 hp4 hp9) (hp-heal hp13 hp5 hp10) (hp-heal hp13 hp6 hp11) (hp-heal hp13 hp7 hp12) (hp-heal hp13 hp8 hp13) (hp-heal hp13 hp9 hp13) (hp-heal hp13 hp10 hp13) (hp-heal hp13 hp11 hp13) (hp-heal hp13 hp12 hp13) (hp-heal hp13 hp13 hp13)
    (hp-heal hp14 (:objects depths) (hp-heal hp14 firelink catacombs) (hp-heal hp14 workshop fortress) (hp-heal hp14 burg throne) (hp-heal hp14 parish -) (hp-heal hp14 depths location) (hp-heal hp14 catacombs master-key) (hp-heal hp14 fortress catacombs-key) (hp-heal hp14 throne -) (hp-heal hp14 - key) (hp-heal hp14 location hollow) (hp-heal hp14 master-key bandit) (hp-heal hp14 catacombs-key skeleton) (hp-heal hp14 - giant) (hp-heal hp14 key -) (hp-heal hp14 hollow minor-enemy) (hp-heal hp14 bandit gaping-dragon) (hp-heal hp14 skeleton iron-golem) (hp-heal hp14 giant final-lord) (hp-heal hp14 - -) (hp-heal hp14 minor-enemy boss) (hp-heal hp14 gaping-dragon hp0) (hp-heal hp14 iron-golem hp1) (hp-heal hp14 final-lord hp2) (hp-heal hp14 - hp3) (hp-heal hp14 boss hp4) (hp-heal hp14 hp0 hp5) (hp-heal hp14 hp1 hp6) (hp-heal hp14 hp2 hp7) (hp-heal hp14 hp3 hp8) (hp-heal hp14 hp4 hp9) (hp-heal hp14 hp5 hp10) (hp-heal hp14 hp6 hp11) (hp-heal hp14 hp7 hp12) (hp-heal hp14 hp8 hp13) (hp-heal hp14 hp9 hp14) (hp-heal hp14 hp10 hp14) (hp-heal hp14 hp11 hp14) (hp-heal hp14 hp12 hp14) (hp-heal hp14 hp13 hp14) (hp-heal hp14 hp14 hp14)
    (hp-heal hp15 (:objects depths) (hp-heal hp15 firelink catacombs) (hp-heal hp15 workshop fortress) (hp-heal hp15 burg throne) (hp-heal hp15 parish -) (hp-heal hp15 depths location) (hp-heal hp15 catacombs master-key) (hp-heal hp15 fortress catacombs-key) (hp-heal hp15 throne -) (hp-heal hp15 - key) (hp-heal hp15 location hollow) (hp-heal hp15 master-key bandit) (hp-heal hp15 catacombs-key skeleton) (hp-heal hp15 - giant) (hp-heal hp15 key -) (hp-heal hp15 hollow minor-enemy) (hp-heal hp15 bandit gaping-dragon) (hp-heal hp15 skeleton iron-golem) (hp-heal hp15 giant final-lord) (hp-heal hp15 - -) (hp-heal hp15 minor-enemy boss) (hp-heal hp15 gaping-dragon hp0) (hp-heal hp15 iron-golem hp1) (hp-heal hp15 final-lord hp2) (hp-heal hp15 - hp3) (hp-heal hp15 boss hp4) (hp-heal hp15 hp0 hp5) (hp-heal hp15 hp1 hp6) (hp-heal hp15 hp2 hp7) (hp-heal hp15 hp3 hp8) (hp-heal hp15 hp4 hp9) (hp-heal hp15 hp5 hp10) (hp-heal hp15 hp6 hp11) (hp-heal hp15 hp7 hp12) (hp-heal hp15 hp8 hp13) (hp-heal hp15 hp9 hp14) (hp-heal hp15 hp10 hp15) (hp-heal hp15 hp11 hp15) (hp-heal hp15 hp12 hp15) (hp-heal hp15 hp13 hp15) (hp-heal hp15 hp14 hp15) (hp-heal hp15 hp15 hp15)
    (hp-heal hp16 (:objects depths) (hp-heal hp16 firelink catacombs) (hp-heal hp16 workshop fortress) (hp-heal hp16 burg throne) (hp-heal hp16 parish -) (hp-heal hp16 depths location) (hp-heal hp16 catacombs master-key) (hp-heal hp16 fortress catacombs-key) (hp-heal hp16 throne -) (hp-heal hp16 - key) (hp-heal hp16 location hollow) (hp-heal hp16 master-key bandit) (hp-heal hp16 catacombs-key skeleton) (hp-heal hp16 - giant) (hp-heal hp16 key -) (hp-heal hp16 hollow minor-enemy) (hp-heal hp16 bandit gaping-dragon) (hp-heal hp16 skeleton iron-golem) (hp-heal hp16 giant final-lord) (hp-heal hp16 - -) (hp-heal hp16 minor-enemy boss) (hp-heal hp16 gaping-dragon hp0) (hp-heal hp16 iron-golem hp1) (hp-heal hp16 final-lord hp2) (hp-heal hp16 - hp3) (hp-heal hp16 boss hp4) (hp-heal hp16 hp0 hp5) (hp-heal hp16 hp1 hp6) (hp-heal hp16 hp2 hp7) (hp-heal hp16 hp3 hp8) (hp-heal hp16 hp4 hp9) (hp-heal hp16 hp5 hp10) (hp-heal hp16 hp6 hp11) (hp-heal hp16 hp7 hp12) (hp-heal hp16 hp8 hp13) (hp-heal hp16 hp9 hp14) (hp-heal hp16 hp10 hp15) (hp-heal hp16 hp11 hp16) (hp-heal hp16 hp12 hp16) (hp-heal hp16 hp13 hp16) (hp-heal hp16 hp14 hp16) (hp-heal hp16 hp15 hp16) (hp-heal hp16 hp16 hp16)
    (hp-heal hp17 (:objects depths) (hp-heal hp17 firelink catacombs) (hp-heal hp17 workshop fortress) (hp-heal hp17 burg throne) (hp-heal hp17 parish -) (hp-heal hp17 depths location) (hp-heal hp17 catacombs master-key) (hp-heal hp17 fortress catacombs-key) (hp-heal hp17 throne -) (hp-heal hp17 - key) (hp-heal hp17 location hollow) (hp-heal hp17 master-key bandit) (hp-heal hp17 catacombs-key skeleton) (hp-heal hp17 - giant) (hp-heal hp17 key -) (hp-heal hp17 hollow minor-enemy) (hp-heal hp17 bandit gaping-dragon) (hp-heal hp17 skeleton iron-golem) (hp-heal hp17 giant final-lord) (hp-heal hp17 - -) (hp-heal hp17 minor-enemy boss) (hp-heal hp17 gaping-dragon hp0) (hp-heal hp17 iron-golem hp1) (hp-heal hp17 final-lord hp2) (hp-heal hp17 - hp3) (hp-heal hp17 boss hp4) (hp-heal hp17 hp0 hp5) (hp-heal hp17 hp1 hp6) (hp-heal hp17 hp2 hp7) (hp-heal hp17 hp3 hp8) (hp-heal hp17 hp4 hp9) (hp-heal hp17 hp5 hp10) (hp-heal hp17 hp6 hp11) (hp-heal hp17 hp7 hp12) (hp-heal hp17 hp8 hp13) (hp-heal hp17 hp9 hp14) (hp-heal hp17 hp10 hp15) (hp-heal hp17 hp11 hp16) (hp-heal hp17 hp12 hp17) (hp-heal hp17 hp13 hp17) (hp-heal hp17 hp14 hp17) (hp-heal hp17 hp15 hp17) (hp-heal hp17 hp16 hp17) (hp-heal hp17 hp17 hp17)
    (hp-heal hp18 (:objects depths) (hp-heal hp18 firelink catacombs) (hp-heal hp18 workshop fortress) (hp-heal hp18 burg throne) (hp-heal hp18 parish -) (hp-heal hp18 depths location) (hp-heal hp18 catacombs master-key) (hp-heal hp18 fortress catacombs-key) (hp-heal hp18 throne -) (hp-heal hp18 - key) (hp-heal hp18 location hollow) (hp-heal hp18 master-key bandit) (hp-heal hp18 catacombs-key skeleton) (hp-heal hp18 - giant) (hp-heal hp18 key -) (hp-heal hp18 hollow minor-enemy) (hp-heal hp18 bandit gaping-dragon) (hp-heal hp18 skeleton iron-golem) (hp-heal hp18 giant final-lord) (hp-heal hp18 - -) (hp-heal hp18 minor-enemy boss) (hp-heal hp18 gaping-dragon hp0) (hp-heal hp18 iron-golem hp1) (hp-heal hp18 final-lord hp2) (hp-heal hp18 - hp3) (hp-heal hp18 boss hp4) (hp-heal hp18 hp0 hp5) (hp-heal hp18 hp1 hp6) (hp-heal hp18 hp2 hp7) (hp-heal hp18 hp3 hp8) (hp-heal hp18 hp4 hp9) (hp-heal hp18 hp5 hp10) (hp-heal hp18 hp6 hp11) (hp-heal hp18 hp7 hp12) (hp-heal hp18 hp8 hp13) (hp-heal hp18 hp9 hp14) (hp-heal hp18 hp10 hp15) (hp-heal hp18 hp11 hp16) (hp-heal hp18 hp12 hp17) (hp-heal hp18 hp13 hp18) (hp-heal hp18 hp14 hp18) (hp-heal hp18 hp15 hp18) (hp-heal hp18 hp16 hp18) (hp-heal hp18 hp17 hp18) (hp-heal hp18 hp18 hp18)
    (hp-heal hp19 (:objects depths) (hp-heal hp19 firelink catacombs) (hp-heal hp19 workshop fortress) (hp-heal hp19 burg throne) (hp-heal hp19 parish -) (hp-heal hp19 depths location) (hp-heal hp19 catacombs master-key) (hp-heal hp19 fortress catacombs-key) (hp-heal hp19 throne -) (hp-heal hp19 - key) (hp-heal hp19 location hollow) (hp-heal hp19 master-key bandit) (hp-heal hp19 catacombs-key skeleton) (hp-heal hp19 - giant) (hp-heal hp19 key -) (hp-heal hp19 hollow minor-enemy) (hp-heal hp19 bandit gaping-dragon) (hp-heal hp19 skeleton iron-golem) (hp-heal hp19 giant final-lord) (hp-heal hp19 - -) (hp-heal hp19 minor-enemy boss) (hp-heal hp19 gaping-dragon hp0) (hp-heal hp19 iron-golem hp1) (hp-heal hp19 final-lord hp2) (hp-heal hp19 - hp3) (hp-heal hp19 boss hp4) (hp-heal hp19 hp0 hp5) (hp-heal hp19 hp1 hp6) (hp-heal hp19 hp2 hp7) (hp-heal hp19 hp3 hp8) (hp-heal hp19 hp4 hp9) (hp-heal hp19 hp5 hp10) (hp-heal hp19 hp6 hp11) (hp-heal hp19 hp7 hp12) (hp-heal hp19 hp8 hp13) (hp-heal hp19 hp9 hp14) (hp-heal hp19 hp10 hp15) (hp-heal hp19 hp11 hp16) (hp-heal hp19 hp12 hp17) (hp-heal hp19 hp13 hp18) (hp-heal hp19 hp14 hp19) (hp-heal hp19 hp15 hp19) (hp-heal hp19 hp16 hp19) (hp-heal hp19 hp17 hp19) (hp-heal hp19 hp18 hp19) (hp-heal hp19 hp19 hp19)
    (hp-heal hp20 (:objects depths) (hp-heal hp20 firelink catacombs) (hp-heal hp20 workshop fortress) (hp-heal hp20 burg throne) (hp-heal hp20 parish -) (hp-heal hp20 depths location) (hp-heal hp20 catacombs master-key) (hp-heal hp20 fortress catacombs-key) (hp-heal hp20 throne -) (hp-heal hp20 - key) (hp-heal hp20 location hollow) (hp-heal hp20 master-key bandit) (hp-heal hp20 catacombs-key skeleton) (hp-heal hp20 - giant) (hp-heal hp20 key -) (hp-heal hp20 hollow minor-enemy) (hp-heal hp20 bandit gaping-dragon) (hp-heal hp20 skeleton iron-golem) (hp-heal hp20 giant final-lord) (hp-heal hp20 - -) (hp-heal hp20 minor-enemy boss) (hp-heal hp20 gaping-dragon hp0) (hp-heal hp20 iron-golem hp1) (hp-heal hp20 final-lord hp2) (hp-heal hp20 - hp3) (hp-heal hp20 boss hp4) (hp-heal hp20 hp0 hp5) (hp-heal hp20 hp1 hp6) (hp-heal hp20 hp2 hp7) (hp-heal hp20 hp3 hp8) (hp-heal hp20 hp4 hp9) (hp-heal hp20 hp5 hp10) (hp-heal hp20 hp6 hp11) (hp-heal hp20 hp7 hp12) (hp-heal hp20 hp8 hp13) (hp-heal hp20 hp9 hp14) (hp-heal hp20 hp10 hp15) (hp-heal hp20 hp11 hp16) (hp-heal hp20 hp12 hp17) (hp-heal hp20 hp13 hp18) (hp-heal hp20 hp14 hp19) (hp-heal hp20 hp15 hp20) (hp-heal hp20 hp16 hp20) (hp-heal hp20 hp17 hp20) (hp-heal hp20 hp18 hp20) (hp-heal hp20 hp19 hp20) (hp-heal hp20 hp20 hp20)
    (player-max-hp hp10) (player-hp hp10)
    (player-current-level pl0)
    (player-level-next pl0 pl1) (player-level-next pl1 pl2) (player-level-next pl2 pl3) (player-level-next pl3 pl4) (player-level-next pl4 pl5)
    (player-weapon-level w0) (wlevel-next w0 w1)
    (boss-phase-zero bp0)
    (boss-phase-next bp6 bp5) (boss-phase-next bp5 bp4) (boss-phase-next bp4 bp3) (boss-phase-next bp3 bp2) (boss-phase-next bp2 bp1) (boss-phase-next bp1 bp0)
    (boss-phase-next bp7 bp6)
    (boss-max-phase gaping-dragon bp6) (boss-current-phase gaping-dragon bp6)
    (boss-max-phase iron-golem bp6) (boss-current-phase iron-golem bp6)
    (boss-max-phase final-lord bp7) (boss-current-phase final-lord bp7)
    (estus-unlocked e1) (estus-full e1) (estus-unlocked e2) (estus-full e2) (estus-unlocked e3) (estus-full e3)
    (soul-next s0 s1) (soul-next s1 s2) (soul-next s2 s3) (soul-next s3 s4) (soul-next s4 s5)
    (hp-after-attack bandit hp20 hp19)
    (hp-after-attack bandit hp19 hp18)
    (hp-after-attack bandit hp18 hp17)
    (hp-after-attack bandit hp17 hp16)
    (hp-after-attack bandit hp16 hp15)
    (hp-after-attack bandit hp15 hp14)
    (hp-after-attack bandit hp14 hp13)
    (hp-after-attack bandit hp13 hp12)
    (hp-after-attack bandit hp12 hp11)
    (hp-after-attack bandit hp11 hp10)
    (hp-after-attack bandit hp10 hp9)
    (hp-after-attack bandit hp9 hp8)
    (hp-after-attack bandit hp8 hp7)
    (hp-after-attack bandit hp7 hp6)
    (hp-after-attack bandit hp6 hp5)
    (hp-after-attack bandit hp5 hp4)
    (hp-after-attack bandit hp4 hp3)
    (hp-after-attack bandit hp3 hp2)
    (hp-after-attack bandit hp2 hp1)
    (hp-after-attack bandit hp1 hp0)
    (hp-after-attack final-lord hp20 hp18)
    (hp-after-attack final-lord hp19 hp17)
    (hp-after-attack final-lord hp18 hp16)
    (hp-after-attack final-lord hp17 hp15)
    (hp-after-attack final-lord hp16 hp14)
    (hp-after-attack final-lord hp15 hp13)
    (hp-after-attack final-lord hp14 hp12)
    (hp-after-attack final-lord hp13 hp11)
    (hp-after-attack final-lord hp12 hp10)
    (hp-after-attack final-lord hp11 hp9)
    (hp-after-attack final-lord hp10 hp8)
    (hp-after-attack final-lord hp9 hp7)
    (hp-after-attack final-lord hp8 hp6)
    (hp-after-attack final-lord hp7 hp5)
    (hp-after-attack final-lord hp6 hp4)
    (hp-after-attack final-lord hp5 hp3)
    (hp-after-attack final-lord hp4 hp2)
    (hp-after-attack final-lord hp3 hp1)
    (hp-after-attack final-lord hp2 hp0)
    (hp-after-attack final-lord hp1 hp0)
    (hp-after-attack gaping-dragon hp20 hp19)
    (hp-after-attack gaping-dragon hp19 hp18)
    (hp-after-attack gaping-dragon hp18 hp17)
    (hp-after-attack gaping-dragon hp17 hp16)
    (hp-after-attack gaping-dragon hp16 hp15)
    (hp-after-attack gaping-dragon hp15 hp14)
    (hp-after-attack gaping-dragon hp14 hp13)
    (hp-after-attack gaping-dragon hp13 hp12)
    (hp-after-attack gaping-dragon hp12 hp11)
    (hp-after-attack gaping-dragon hp11 hp10)
    (hp-after-attack gaping-dragon hp10 hp9)
    (hp-after-attack gaping-dragon hp9 hp8)
    (hp-after-attack gaping-dragon hp8 hp7)
    (hp-after-attack gaping-dragon hp7 hp6)
    (hp-after-attack gaping-dragon hp6 hp5)
    (hp-after-attack gaping-dragon hp5 hp4)
    (hp-after-attack gaping-dragon hp4 hp3)
    (hp-after-attack gaping-dragon hp3 hp2)
    (hp-after-attack gaping-dragon hp2 hp1)
    (hp-after-attack gaping-dragon hp1 hp0)
    (hp-after-attack giant hp20 hp18)
    (hp-after-attack giant hp19 hp17)
    (hp-after-attack giant hp18 hp16)
    (hp-after-attack giant hp17 hp15)
    (hp-after-attack giant hp16 hp14)
    (hp-after-attack giant hp15 hp13)
    (hp-after-attack giant hp14 hp12)
    (hp-after-attack giant hp13 hp11)
    (hp-after-attack giant hp12 hp10)
    (hp-after-attack giant hp11 hp9)
    (hp-after-attack giant hp10 hp8)
    (hp-after-attack giant hp9 hp7)
    (hp-after-attack giant hp8 hp6)
    (hp-after-attack giant hp7 hp5)
    (hp-after-attack giant hp6 hp4)
    (hp-after-attack giant hp5 hp3)
    (hp-after-attack giant hp4 hp2)
    (hp-after-attack giant hp3 hp1)
    (hp-after-attack giant hp2 hp0)
    (hp-after-attack giant hp1 hp0)
    (hp-after-attack hollow hp20 hp19)
    (hp-after-attack hollow hp19 hp18)
    (hp-after-attack hollow hp18 hp17)
    (hp-after-attack hollow hp17 hp16)
    (hp-after-attack hollow hp16 hp15)
    (hp-after-attack hollow hp15 hp14)
    (hp-after-attack hollow hp14 hp13)
    (hp-after-attack hollow hp13 hp12)
    (hp-after-attack hollow hp12 hp11)
    (hp-after-attack hollow hp11 hp10)
    (hp-after-attack hollow hp10 hp9)
    (hp-after-attack hollow hp9 hp8)
    (hp-after-attack hollow hp8 hp7)
    (hp-after-attack hollow hp7 hp6)
    (hp-after-attack hollow hp6 hp5)
    (hp-after-attack hollow hp5 hp4)
    (hp-after-attack hollow hp4 hp3)
    (hp-after-attack hollow hp3 hp2)
    (hp-after-attack hollow hp2 hp1)
    (hp-after-attack hollow hp1 hp0)
    (hp-after-attack iron-golem hp20 hp18)
    (hp-after-attack iron-golem hp19 hp17)
    (hp-after-attack iron-golem hp18 hp16)
    (hp-after-attack iron-golem hp17 hp15)
    (hp-after-attack iron-golem hp16 hp14)
    (hp-after-attack iron-golem hp15 hp13)
    (hp-after-attack iron-golem hp14 hp12)
    (hp-after-attack iron-golem hp13 hp11)
    (hp-after-attack iron-golem hp12 hp10)
    (hp-after-attack iron-golem hp11 hp9)
    (hp-after-attack iron-golem hp10 hp8)
    (hp-after-attack iron-golem hp9 hp7)
    (hp-after-attack iron-golem hp8 hp6)
    (hp-after-attack iron-golem hp7 hp5)
    (hp-after-attack iron-golem hp6 hp4)
    (hp-after-attack iron-golem hp5 hp3)
    (hp-after-attack iron-golem hp4 hp2)
    (hp-after-attack iron-golem hp3 hp1)
    (hp-after-attack iron-golem hp2 hp0)
    (hp-after-attack iron-golem hp1 hp0)
    (hp-after-attack skeleton hp20 hp19)
    (hp-after-attack skeleton hp19 hp18)
    (hp-after-attack skeleton hp18 hp17)
    (hp-after-attack skeleton hp17 hp16)
    (hp-after-attack skeleton hp16 hp15)
    (hp-after-attack skeleton hp15 hp14)
    (hp-after-attack skeleton hp14 hp13)
    (hp-after-attack skeleton hp13 hp12)
    (hp-after-attack skeleton hp12 hp11)
    (hp-after-attack skeleton hp11 hp10)
    (hp-after-attack skeleton hp10 hp9)
    (hp-after-attack skeleton hp9 hp8)
    (hp-after-attack skeleton hp8 hp7)
    (hp-after-attack skeleton hp7 hp6)
    (hp-after-attack skeleton hp6 hp5)
    (hp-after-attack skeleton hp5 hp4)
    (hp-after-attack skeleton hp4 hp3)
    (hp-after-attack skeleton hp3 hp2)
    (hp-after-attack skeleton hp2 hp1)
    (hp-after-attack skeleton hp1 hp0)
    ;; Souls Lader
    (player-max-souls s5) (player-souls s0) (soul-min s0)
    (soul-after-drop hollow s0 s2) (soul-after-drop hollow s1 s3) (soul-after-drop hollow s2 s4) (soul-after-drop hollow s3 s5) (soul-after-drop hollow s4 s5) (soul-after-drop hollow s5 s5)
    (soul-after-drop bandit s0 s2) (soul-after-drop bandit s1 s3) (soul-after-drop bandit s2 s4) (soul-after-drop bandit s3 s5) (soul-after-drop bandit s4 s5) (soul-after-drop bandit s5 s5)
    (soul-after-drop skeleton s0 s2) (soul-after-drop skeleton s1 s3) (soul-after-drop skeleton s2 s4) (soul-after-drop skeleton s3 s5) (soul-after-drop skeleton s4 s5) (soul-after-drop skeleton s5 s5)
    (soul-after-drop giant s0 s2) (soul-after-drop giant s1 s3) (soul-after-drop giant s2 s4) (soul-after-drop giant s3 s5) (soul-after-drop giant s4 s5) (soul-after-drop giant s5 s5)
    (soul-after-drop gaping-dragon s0 s4) (soul-after-drop gaping-dragon s1 s5) (soul-after-drop gaping-dragon s2 s5) (soul-after-drop gaping-dragon s3 s5) (soul-after-drop gaping-dragon s4 s5) (soul-after-drop gaping-dragon s5 s5)
    (soul-after-drop iron-golem s0 s4) (soul-after-drop iron-golem s1 s5) (soul-after-drop iron-golem s2 s5) (soul-after-drop iron-golem s3 s5) (soul-after-drop iron-golem s4 s5) (soul-after-drop iron-golem s5 s5)
    (soul-after-drop final-lord s0 s5) (soul-after-drop final-lord s1 s5) (soul-after-drop final-lord s2 s5) (soul-after-drop final-lord s3 s5) (soul-after-drop final-lord s4 s5) (soul-after-drop final-lord s5 s5)
    (soul-spend-for-level pl0 pl1 s1 s0) (soul-spend-for-level pl0 pl1 s2 s1) (soul-spend-for-level pl0 pl1 s3 s2) (soul-spend-for-level pl0 pl1 s4 s3) (soul-spend-for-level pl0 pl1 s5 s4)
    (soul-spend-for-level pl1 pl2 s2 s0) (soul-spend-for-level pl1 pl2 s3 s1) (soul-spend-for-level pl1 pl2 s4 s2) (soul-spend-for-level pl1 pl2 s5 s3)
    (soul-spend-for-level pl2 pl3 s3 s0) (soul-spend-for-level pl2 pl3 s4 s1) (soul-spend-for-level pl2 pl3 s5 s2)
    (soul-spend-for-level pl3 pl4 s4 s0) (soul-spend-for-level pl3 pl4 s5 s1)
    (soul-spend-for-level pl4 pl5 s5 s0)
    (can-damage-boss gaping-dragon w0)
    (can-damage-boss iron-golem w1)
    (can-damage-boss final-lord w1)
    (= (total-cost) 0)
  )
  (:goal (and
    (deposited-soul gaping-dragon)
    (deposited-soul iron-golem)
    (deposited-soul final-lord)
  ))
  (:metric minimize (total-cost))
)
