;; BENCHMARK 10-FD: Epic Challenge - Large complex problem
(define (problem bench-10-fd)
  (:domain dark-souls-fd)
  (:objects
    firelink workshop burg parish depths catacombs fortress throne - location
    master-key catacombs-key - key
    hollow bandit skeleton giant - minor-enemy
    gaping-dragon iron-golem final-lord - boss
    hp0 hp1 hp2 hp3 hp4 hp5 - hp-level
    w0 w1 - wlevel
    pl0 pl1 - player-level
    bp0 bp1 bp2 bp3 bp4 bp5 bp6 bp7 - boss-phase
    e1 e2 e3 e4 e5 e6 - estus-slot
    s0 s1 s2 s3 s4 s5 s6 s7 s8 - soul-level
  )
  (:init
    (connected firelink workshop) (connected workshop firelink)
    (connected firelink burg) (connected burg firelink)
    (connected burg parish) (connected parish burg)
    (connected parish depths) (connected depths parish)
    (connected firelink catacombs) (connected catacombs firelink)
    (connected catacombs fortress) (connected fortress catacombs)
    (connected fortress throne) (connected throne fortress)
    (locked parish depths) (locked depths parish)
    (locked catacombs fortress) (locked fortress catacombs)
    (can-open-shortcut parish firelink)
    (can-open-shortcut fortress catacombs)
    (is-firelink firelink) (has-bonfire firelink) (has-bonfire parish) (has-bonfire fortress)
    (is-blacksmith workshop)
    (key-at master-key burg) (key-at catacombs-key depths)
    (matches master-key parish depths) (matches catacombs-key catacombs fortress)
    (titanite-at workshop)
    (enemy-at hollow burg) (enemy-at bandit parish) (enemy-at skeleton catacombs) (enemy-at giant fortress)
    (is-alive hollow) (is-alive bandit) (is-alive skeleton) (is-alive giant)
    (enemy-at gaping-dragon depths) (enemy-at iron-golem fortress) (enemy-at final-lord throne)
    (is-alive gaping-dragon) (is-alive iron-golem) (is-alive final-lord)
    (has-active-boss depths) (has-active-boss fortress) (has-active-boss throne)
    (at-player firelink) (last-rested-bonfire firelink)
    (hp-next hp0 hp1) (hp-next hp1 hp2) (hp-next hp2 hp3) (hp-next hp3 hp4) (hp-next hp4 hp5)
    (hp-zero hp0)
    (hp-leq hp0 hp0) (hp-leq hp0 hp1) (hp-leq hp0 hp2) (hp-leq hp0 hp3) (hp-leq hp0 hp4) (hp-leq hp0 hp5)
    (hp-leq hp1 hp1) (hp-leq hp1 hp2) (hp-leq hp1 hp3) (hp-leq hp1 hp4) (hp-leq hp1 hp5)
    (hp-leq hp2 hp2) (hp-leq hp2 hp3) (hp-leq hp2 hp4) (hp-leq hp2 hp5)
    (hp-leq hp3 hp3) (hp-leq hp3 hp4) (hp-leq hp3 hp5)
    (hp-leq hp4 hp4) (hp-leq hp4 hp5)
    (hp-leq hp5 hp5)
    (player-max-hp hp5) (player-hp hp5)
    (player-current-level pl0) (player-level-next pl0 pl1)
    (player-weapon-level w0) (wlevel-next w0 w1)
    (boss-phase-zero bp0)
    (boss-phase-next bp6 bp5) (boss-phase-next bp5 bp4) (boss-phase-next bp4 bp3) (boss-phase-next bp3 bp2) (boss-phase-next bp2 bp1) (boss-phase-next bp1 bp0)
    (boss-phase-next bp7 bp6)
    (boss-max-phase gaping-dragon bp6) (boss-current-phase gaping-dragon bp6)
    (boss-max-phase iron-golem bp6) (boss-current-phase iron-golem bp6)
    (boss-max-phase final-lord bp7) (boss-current-phase final-lord bp7)
    (estus-unlocked e1) (estus-full e1) (estus-unlocked e2) (estus-full e2) (estus-unlocked e3) (estus-full e3)
    (soul-next s0 s1) (soul-next s1 s2) (soul-next s2 s3) (soul-next s3 s4) (soul-next s4 s5) (soul-next s5 s6) (soul-next s6 s7) (soul-next s7 s8)
    (player-max-souls s8) (player-souls s0)
    (hp-after-attack hollow hp5 hp4) (hp-after-attack hollow hp4 hp3) (hp-after-attack hollow hp3 hp2) (hp-after-attack hollow hp2 hp1) (hp-after-attack hollow hp1 hp0)
    (hp-after-attack bandit hp5 hp4) (hp-after-attack bandit hp4 hp3) (hp-after-attack bandit hp3 hp2) (hp-after-attack bandit hp2 hp1) (hp-after-attack bandit hp1 hp0)
    (hp-after-attack skeleton hp5 hp4) (hp-after-attack skeleton hp4 hp3) (hp-after-attack skeleton hp3 hp2) (hp-after-attack skeleton hp2 hp1) (hp-after-attack skeleton hp1 hp0)
    (hp-after-attack giant hp5 hp3) (hp-after-attack giant hp4 hp2) (hp-after-attack giant hp3 hp1) (hp-after-attack giant hp2 hp0) (hp-after-attack giant hp1 hp0)
    (hp-after-attack gaping-dragon hp5 hp4) (hp-after-attack gaping-dragon hp4 hp3) (hp-after-attack gaping-dragon hp3 hp2) (hp-after-attack gaping-dragon hp2 hp1) (hp-after-attack gaping-dragon hp1 hp0)
    (hp-after-attack iron-golem hp5 hp3) (hp-after-attack iron-golem hp4 hp2) (hp-after-attack iron-golem hp3 hp1) (hp-after-attack iron-golem hp2 hp0) (hp-after-attack iron-golem hp1 hp0)
    (hp-after-attack final-lord hp5 hp3) (hp-after-attack final-lord hp4 hp2) (hp-after-attack final-lord hp3 hp1) (hp-after-attack final-lord hp2 hp0) (hp-after-attack final-lord hp1 hp0)
    (soul-after-drop hollow s0 s2) (soul-after-drop hollow s1 s3) (soul-after-drop hollow s2 s4) (soul-after-drop hollow s3 s5) (soul-after-drop hollow s4 s6) (soul-after-drop hollow s5 s7) (soul-after-drop hollow s6 s8) (soul-after-drop hollow s7 s8) (soul-after-drop hollow s8 s8)
    (soul-after-drop bandit s0 s2) (soul-after-drop bandit s1 s3) (soul-after-drop bandit s2 s4) (soul-after-drop bandit s3 s5) (soul-after-drop bandit s4 s6) (soul-after-drop bandit s5 s7) (soul-after-drop bandit s6 s8) (soul-after-drop bandit s7 s8) (soul-after-drop bandit s8 s8)
    (soul-after-drop skeleton s0 s2) (soul-after-drop skeleton s1 s3) (soul-after-drop skeleton s2 s4) (soul-after-drop skeleton s3 s5) (soul-after-drop skeleton s4 s6) (soul-after-drop skeleton s5 s7) (soul-after-drop skeleton s6 s8) (soul-after-drop skeleton s7 s8) (soul-after-drop skeleton s8 s8)
    (soul-after-drop giant s0 s2) (soul-after-drop giant s1 s3) (soul-after-drop giant s2 s4) (soul-after-drop giant s3 s5) (soul-after-drop giant s4 s6) (soul-after-drop giant s5 s7) (soul-after-drop giant s6 s8) (soul-after-drop giant s7 s8) (soul-after-drop giant s8 s8)
    (soul-after-drop gaping-dragon s0 s4) (soul-after-drop gaping-dragon s1 s5) (soul-after-drop gaping-dragon s2 s6) (soul-after-drop gaping-dragon s3 s7) (soul-after-drop gaping-dragon s4 s8) (soul-after-drop gaping-dragon s5 s8) (soul-after-drop gaping-dragon s6 s8) (soul-after-drop gaping-dragon s7 s8) (soul-after-drop gaping-dragon s8 s8)
    (soul-after-drop iron-golem s0 s4) (soul-after-drop iron-golem s1 s5) (soul-after-drop iron-golem s2 s6) (soul-after-drop iron-golem s3 s7) (soul-after-drop iron-golem s4 s8) (soul-after-drop iron-golem s5 s8) (soul-after-drop iron-golem s6 s8) (soul-after-drop iron-golem s7 s8) (soul-after-drop iron-golem s8 s8)
    (soul-after-drop final-lord s0 s5) (soul-after-drop final-lord s1 s6) (soul-after-drop final-lord s2 s7) (soul-after-drop final-lord s3 s8) (soul-after-drop final-lord s4 s8) (soul-after-drop final-lord s5 s8) (soul-after-drop final-lord s6 s8) (soul-after-drop final-lord s7 s8) (soul-after-drop final-lord s8 s8)
    (soul-spend-for-level pl0 pl1 s2 s0) (soul-spend-for-level pl0 pl1 s3 s1) (soul-spend-for-level pl0 pl1 s4 s2) (soul-spend-for-level pl0 pl1 s5 s3) (soul-spend-for-level pl0 pl1 s6 s4) (soul-spend-for-level pl0 pl1 s7 s5) (soul-spend-for-level pl0 pl1 s8 s6)
    (can-damage-boss gaping-dragon w0)
    (can-damage-boss iron-golem w1)
    (can-damage-boss final-lord w1)
    (= (total-cost) 0)
  )
  (:goal (and
    (deposited-soul gaping-dragon)
    (deposited-soul iron-golem)
    (deposited-soul final-lord)
  ))
  (:metric minimize (total-cost))
)
